### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by FrederikBolding** [deamme/usecrypto#19]

**Comment by deamme** [comment]
Use https://metatags.io/ to generate tags

**Comment by FrederikBolding** [comment]
Yep, we just need to decide on a description and an image to use.

**Comment by deamme** [comment]
Use this link for the preview image: https://screenshot-v2.now.sh/usecrypto.xyz

EDIT: I can see that it's not caching right now, so perhaps we need to make our own endpoint.

**Comment by deamme** [comment]
Use this new endpoint instead which has a caching mechanism:
https://webshot.deam.io/usecrypto.xyz

**Comment by FrederikBolding** [comment]
@deamme  Added initial SEO in https://github.com/deamme/usecrypto/commit/f02329fbca1ea59797bb3d009fe76965b5671b6e

**Comment by deamme** [comment]
@FrederikBolding Looks good to me for now
